---
#####
#
# @name MyINFRA.eu ~ Ansible Issue Role
# @version 2025.07.001
# @since 2025.07.001
#
# @copyright (c) 2025 (and beyond) - Dennis de Houx, All In One, One For The code
# @author Dennis de Houx <dennis@dehoux.be>
# @license https://creativecommons.org/licenses/by-nc-nd/4.0/deed.en CC BY-NC-ND 4.0
#
###
#
# Ansible role to manage issue & issue.net files.
#
#####

- name: "Copyright & Version information"
  ansible.builtin.debug:
    msg:
      - "MyINFRA.eu ~ Ansible <name> Role"
      - "Version   : {{ myinfra_eu.issue.version }}"
      - "Copyright : (c) 2025 (and beyond) - Dennis de Houx, All In One, One For The code"
      - "Author    : Dennis de Houx <dennis@dehoux.be>"
      - "License   : https://creativecommons.org/licenses/by-nc-nd/4.0/deed.en CC BY-NC-ND 4.0"

- name: "ISSUE > Create/Manage Issue File"
  ansible.builtin.copy:
    src: "{{ src_file }}"
    dest: /etc/issue
    owner: root
    group: root
    mode: "0644"
    backup: true
  vars:
    src_file: "{{ issue.path | default('files') + '/issue' }}"
  tags:
    - myinfra_issue

- name: "ISSUE > Create/Manage Issue.net File"
  ansible.builtin.copy:
    src: "{{ src_file }}"
    dest: /etc/issue.net
    owner: root
    group: root
    mode: "0644"
    backup: true
  vars:
    location: "{{ issue.path | default('files') + '/issue.net' }}"
  tags:
    - myinfra_issue
